config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'

  post 'add_to_cart' => 'cart#add_to_cart'

  post 'order_complete' => 'cart#order_complete'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand'

  resources :orders
  resources :line_items
  resources :products

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GimmeMoney</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "GimmeMoney", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Store", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |cat| %>
                <li><%= link_to cat.name, categorical_path(category_id: cat.id)%></li>
              <% end %>
            </ul>
         </li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
           <ul class="dropdown-menu">
             <% @brands.each do |brand| %>
               <li><%= link_to brand, branding_path(brand: brand) %></li>
             <% end %>
             <li><%= link_to 'All', root_path %></li>
          </ul>
        </li> 
        <li><li><a href="/view_order">View Cart <span class="badge"><%= @cart_count %></span></a></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><a href="#"><%= current_user.email %></a></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up",  new_user_registration_path %></li>
          <li><%= link_to "Forgot Password",  new_user_password_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>